# Splitting documents into sentences

In [1]:
import nltk

In [3]:
# Download the first time
# nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\dzhang\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\dzhang\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     C:\Users\dzhang\AppData\Roaming\nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package brown to
[nltk_data]    |     C:\Users\dzhang\AppData\Roaming\nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to
[nltk_data]    |     C:\Users\dzhang\AppData\Roaming\nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to
[nltk_data]    |     C:\Us

[nltk_data]    |   Package propbank is already up-to-date!
[nltk_data]    | Downloading package ptb to
[nltk_data]    |     C:\Users\dzhang\AppData\Roaming\nltk_data...
[nltk_data]    |   Package ptb is already up-to-date!
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     C:\Users\dzhang\AppData\Roaming\nltk_data...
[nltk_data]    |   Package product_reviews_1 is already up-to-date!
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     C:\Users\dzhang\AppData\Roaming\nltk_data...
[nltk_data]    |   Package product_reviews_2 is already up-to-date!
[nltk_data]    | Downloading package pros_cons to
[nltk_data]    |     C:\Users\dzhang\AppData\Roaming\nltk_data...
[nltk_data]    |   Package pros_cons is already up-to-date!
[nltk_data]    | Downloading package qc to
[nltk_data]    |     C:\Users\dzhang\AppData\Roaming\nltk_data...
[nltk_data]    |   Package qc is already up-to-date!
[nltk_data]    | Downloading package reuters to
[nltk_d

[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     C:\Users\dzhang\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping models\word2vec_sample.zip.
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     C:\Users\dzhang\AppData\Roaming\nltk_data...
[nltk_data]    | Downloading package mte_teip5 to
[nltk_data]    |     C:\Users\dzhang\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping corpora\mte_teip5.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\dzhang\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\dzhang\AppData\Roaming\nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers\averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package perluniprops to
[nltk_data]   

True

In [4]:
text = "Mr. Robin Wu loves pandas. He has a Ph.D. in pandology."

In [6]:
tokenized_sentences = nltk.sent_tokenize(text)
for sent in tokenized_sentences:
    print('Sentence: ')
    print(sent)
    print()

Sentence: 
Mr. Robin Wu loves pandas.

Sentence: 
He has a Ph.D. in pandology.



In [8]:
import spacy

In [21]:
from spacy.lang.en import English
nlp = English()
nlp.add_pipe(nlp.create_pipe('sentencizer'))

In [23]:
doc = nlp(text)
for sent in doc.sents:
    print('Sentence: ')
    print(sent.text)
    print()

Sentence: 
Mr. Robin Wu loves pandas.

Sentence: 
He has a Ph.D. in pandology.



# Splitting sentences into words

In [25]:
from nltk.tokenize import word_tokenize
tokens = word_tokenize(text)
print(tokens)

['Mr.', 'Robin', 'Wu', 'loves', 'pandas', '.', 'He', 'has', 'a', 'Ph.D.', 'in', 'pandology', '.']


In [27]:
from spacy.lang.en import English
nlp = English()
tokens = nlp(text)
tokens = [token.orth_ for token in tokens if not token.orth_.isspace()]
print(tokens)

['Mr.', 'Robin', 'Wu', 'loves', 'pandas', '.', 'He', 'has', 'a', 'Ph.D.', 'in', 'pandology', '.']


In [28]:
dir(tokens[0])

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [29]:
def print_token(token):
    print("=====================")
    print("value:", token.orth_)
    print("lemma:", token.lemma_) # lemma is the root of a word
    print("shape:", token.shape_) # shape is capitalization and punctuation

In [31]:
text1 = "Robin had dinner with pandas because he was a friend of theirs."
tokens = nlp(text1)
for token in tokens:
    print_token(token)

value: Robin
lemma: Robin
shape: Xxxxx
value: had
lemma: have
shape: xxx
value: dinner
lemma: dinner
shape: xxxx
value: with
lemma: with
shape: xxxx
value: pandas
lemma: panda
shape: xxxx
value: because
lemma: because
shape: xxxx
value: he
lemma: he
shape: xx
value: was
lemma: be
shape: xxx
value: a
lemma: a
shape: x
value: friend
lemma: friend
shape: xxxx
value: of
lemma: of
shape: xx
value: theirs
lemma: theirs
shape: xxxx
value: .
lemma: .
shape: .


# Filtering out stop words

In [32]:
english_stopwords = set(nltk.corpus.stopwords.words('english'))
print(english_stopwords)

{'once', 'her', 'yours', 'a', 'needn', 'him', 'through', 'any', 'yourselves', 'your', 'm', "isn't", 'such', 'he', 'mightn', 'yourself', "hasn't", 'has', 'some', "didn't", "aren't", 'about', 'while', 'down', "weren't", 'on', 'of', 'have', 'being', 'won', 'their', 'these', 'my', 'did', 's', 'which', 'very', 'between', 'off', 'can', "wasn't", 'll', "mightn't", 'having', 'for', 'why', 'an', 'now', 'our', 'until', 'been', 'there', "you've", 'no', 'nor', 'own', 've', 'couldn', 'had', 'into', 'because', 'hasn', "don't", 'only', 'didn', 'ma', "wouldn't", 'most', 'are', 'ain', 'other', "doesn't", 'then', 'against', 'me', 'aren', 'mustn', "she's", 'it', "needn't", 'that', 'again', 'up', "you're", 'from', 'ours', 'its', 'both', 'd', 'further', 'was', 'but', 'each', "you'll", 'y', 'weren', 'himself', 'myself', 're', "shan't", 'shouldn', 'do', 'itself', 'his', 'out', 'here', 'those', 'ourselves', 'under', 'over', 'the', "should've", 'same', 'they', 'few', 'as', 'we', "it's", 'she', 'when', 'will', 

In [33]:
tokens = word_tokenize(text)
content_tokens = [token for token in tokens if token.lower() not in english_stopwords]
print(content_tokens)

['Mr.', 'Robin', 'Wu', 'loves', 'pandas', '.', 'Ph.D.', 'pandology', '.']


**NLP Bible:**  
2nd edition: http://www.cs.colorado.edu/~martin/slp2.html  
3rd edition: https://web.stanford.edu/~jurafsky/slp3/

# tf-idf Gensim
Going subsymbolic: vector representation
* Converting documents & words into vectors
* Vectors allow for comparisons because you can measure the distance between them
* Useful for finding similar documents or words

### Document similarity with tf-idf in Gensim
Consider a vocabulary of 50,000 different words; each word has a number in that range.  
You could represent a document by putting a 1 in that vector for each word that is in the document and leaving all the other values 0.  
You could then compare the similarity of two documents by looking at the similarities between their two vectors.  

#### Make better document vectors 
**term frequency (tf)**  
Count the number of times the word occurs and put that in the vector as well  
  
  
**inverse document frequency (idf)**-rare words are more important than common words  
1. Multiply each tf value in the vector by a measure of how common it is in the entire set of documents
2. Get idf by dividing the total number of documents N by the number of documents containing the term t, then take the log of that. If D is the document, then
    * idf(t,D) = log(N /# with t)


In [1]:
import gensim

In [10]:
raw_docs = ["Robin loves pandas.",
        "Esme loves to prepare for Tokyo 2020.",
        "I don't choose to take a nap. The nap chooses me.",
        "That man is nice as pie with ice cream.",
        "This pizza is an affront to nature."]

In [3]:
from nltk.tokenize import word_tokenize

In [4]:
# define a function that makes tokens
def get_tokens(text):
    tokens = word_tokenize(text)
    return tokens

In [11]:
# a gensim document is a list of tokens
# we could optionally make all tokens lower case
gen_docs = [get_tokens(text) for text in raw_docs]
print(gen_docs)

[['Robin', 'loves', 'pandas', '.'], ['Esme', 'loves', 'to', 'prepare', 'for', 'Tokyo', '2020', '.'], ['I', 'do', "n't", 'choose', 'to', 'take', 'a', 'nap', '.', 'The', 'nap', 'chooses', 'me', '.'], ['That', 'man', 'is', 'nice', 'as', 'pie', 'with', 'ice', 'cream', '.'], ['This', 'pizza', 'is', 'an', 'affront', 'to', 'nature', '.']]


In [12]:
# create dictionary from a list of documents
# a dictionary maps every word to a number
dictionary = gensim.corpora.Dictionary(gen_docs)
num_words = len(dictionary)
print("Num words in dictionary: {}".format(num_words))
for idx,word in dictionary.items():
    print(idx,word)

Num words in dictionary: 34
0 .
1 Robin
2 loves
3 pandas
4 2020
5 Esme
6 Tokyo
7 for
8 prepare
9 to
10 I
11 The
12 a
13 choose
14 chooses
15 do
16 me
17 n't
18 nap
19 take
20 That
21 as
22 cream
23 ice
24 is
25 man
26 nice
27 pie
28 with
29 This
30 affront
31 an
32 nature
33 pizza


In [14]:
# Two ways to convert token id to string
print(dictionary[13])
print(dictionary.id2token[13])

choose
choose


In [9]:
# convert string to token id
print(dictionary.token2id['man'])

25


In [17]:
# Create bag of words
# A bag of words is tf of tf-idf
# called a "bag of words" because order is lost
bow_doc = dictionary.doc2bow(['Robin', 'loves', 'loves', 'loves', 'pandas', '!'])
print(bow_doc)
# Note that '!' is not listed because it is not in the dictionary

[(1, 1), (2, 3), (3, 1)]


In [18]:
# Create corpus
# A corpus is a list of bag of words
corpus = [dictionary.doc2bow(gen_doc) for gen_doc in gen_docs]
print(corpus)

[[(0, 1), (1, 1), (2, 1), (3, 1)], [(0, 1), (2, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1)], [(0, 2), (9, 1), (10, 1), (11, 1), (12, 1), (13, 1), (14, 1), (15, 1), (16, 1), (17, 1), (18, 2), (19, 1)], [(0, 1), (20, 1), (21, 1), (22, 1), (23, 1), (24, 1), (25, 1), (26, 1), (27, 1), (28, 1)], [(0, 1), (9, 1), (24, 1), (29, 1), (30, 1), (31, 1), (32, 1), (33, 1)]]


In [21]:
# Create tf-idf model from corpus
# num_nnz is the number of tokens
tf_idf = gensim.models.TfidfModel(corpus)
print(tf_idf)

TfidfModel(num_docs=5, num_nnz=42)


In [22]:
# Show document in text form, bow form, and tf-idf
print(gen_docs[0])       # gensim.corpora.Dictionary(gen_docs) generates a dictionary (thus idx)
print(corpus[0])         # (idx, tf)
print(tf_idf[corpus][0]) # (idx, idf)
# 0 .
# 1 Robin
# 2 loves
# 3 pandas
# idf for loves is lower because it occurs multiple times
# idf for '.' is 0 because it occurs in all sentences and log_2(1) = 0
# vectors are normalized so they sum to 1

['Robin', 'loves', 'pandas', '.']
[(0, 1), (1, 1), (2, 1), (3, 1)]
[(1, 0.6559486886294514), (2, 0.37344696513776354), (3, 0.6559486886294514)]


In [24]:
# Show bag of words and tf-idf for new document
# Note it is similar to the document above
bow = dictionary.doc2bow(['Esme', 'loves', 'pizza','.'])
print(bow)
print(tf_idf[bow])

[(0, 1), (2, 1), (5, 1), (33, 1)]
[(2, 0.37344696513776354), (5, 0.6559486886294514), (33, 0.6559486886294514)]


In [26]:
# This is just a confirmation. Create tf-idf vector manually.
from math import log
num_docs = tf_idf.num_docs
idf_1 = log(num_docs/1,2)
idf_2 = log(num_docs/2,2)
# only show nonzero values, and use numpy array
import numpy as np
v = np.array([idf_1, idf_2, idf_1])
print(v)
# normalize to the length is 1
norm_v = np.linalg.norm(v)
print(norm_v)
# show normalized vector
print(v/norm_v)

[2.32192809 1.32192809 2.32192809]
3.539801413032522
[0.65594869 0.37344697 0.65594869]


In [36]:
# Create similarity measure object in tf-idf space
# First arg is temp external storage
# https://radimrehurek.com/gensim/similarities/docsim.html
sims = gensim.similarities.Similarity('/Users/dzhang/Documents/Research/temp', tf_idf[corpus], num_features=len(dictionary))
print(sims)

Similarity index with 5 documents in 0 shards (stored under /Users/dzhang/Documents/Research/temp)


In [37]:
# Create query document and convert to tf-idf
query_doc = "Robin for Tokyo 2020".split()
print(query_doc)
query_doc_bow = dictionary.doc2bow(query_doc)
print(query_doc_bow)    # tf
query_doc_tf_idf = tf_idf[query_doc_bow]
print(query_doc_tf_idf)

['Robin', 'for', 'Tokyo', '2020']
[(1, 1), (4, 1), (6, 1), (7, 1)]
[(1, 0.5), (4, 0.5), (6, 0.5), (7, 0.5)]


In [38]:
# Show array of document similarities to query
sims[query_doc_tf_idf]

C:\Users\dzhang\AppData\Local\Continuum\anaconda3\lib\site-packages\smart_open\smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL
C:\Users\dzhang\AppData\Local\Continuum\anaconda3\lib\site-packages\gensim\similarities\docsim.py:528: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  result = numpy.hstack(shard_results)


array([0.32797435, 0.644016  , 0.        , 0.        , 0.        ],
      dtype=float32)